#pragma once

#define VIAL_KEYBOARD_UID { 0xDA, 0xA5, 0x31, 0x7A, 0xE8, 0xF6, 0xB3, 0xCE }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define DYNAMIC_KEYMAP_MACRO_COUNT 20

#define VIAL_COMBO_ENTRIES 16
#define VIAL_TAP_DANCE_ENTRIES 16
#define VIAL_KEY_OVERRIDE_ENTRIES 16